services:
  backend:
    build: ./backend
    container_name: backend_c1
    ports:
      - "4000:4000"
    env_file:
      - "./backend/.env"

  frontend:
    build: ./frontend
    container_name: frontend_c1
    ports:
      - "5173:5173"
    env_file:
      - "./frontend/.env"
    stdin_open: true
    tty: true
